### ISSUE TITLE
Race condition causing lab to freeze

### ISSUE THREAD

**Issue by mlucool** [Quansight/jupyterlab-kernel-usage#16]
Hi,

Restarting a kernel quickly causes lab's server to freeze (i.e. not just that kernel, but all further operations stop).

This is likely a couple issues: 
1. Lab should never freeze from a plugin
2. There is a bug here and/or in ipykernel/ipython that triggers 1

Reproducer:
IPykernel@6.13.0
IPython@7.32.0
jupyterlab-kernel-usage@0.4.0

In this gif, I use a hotkey to quickly restart the kernel. You'll see at the end new notebooks don't open, this is because the server is blocked. It'll stay deadlocked forever at this point.

https://user-images.githubusercontent.com/1813603/163278508-17f4c415-1d3e-4f20-b073-c33923d1d4ef.mov

_Note: I added/removed things until I found that this extension was the culprit. I don't fully understand what is wrong_

**Comment by echarles** [comment]
@mlucool I have opened https://github.com/Quansight/jupyterlab-kernel-usage/pull/17 in an attempt to fix this.

Before merging, I'd like to be able to fully confirm the fix is correct. Therefor, I try to implement that shortcut to quickly restart kernels without prompts but having hard time with that. I am using the latest jlab version where I have read issues with shortcuts, so I am not sure if somethin is wrong with my settings. Also, how to you configure to skip the user prompt when the kernel is restarting?

**Comment by mlucool** [comment]
I was pushing `0 0` then `enter` to do it quickly many times in a row.

**Comment by echarles** [comment]
I have tried typing as fast as I could the `0 0 Enter` combination. I was not able to break with vanilla jupyterlab. At some point (not always), I have been able to break jupyterlab with this extension.

I think a standard user will restart and wait for kernel be up-again, in that case, there will never be an issue. In case of very fast and consequent restarts, it looks there is a risk to hang. Not sure yet why. In case of restart of distributed kernels (spark, dask...) the risk is prolly higher to break as restart distributed kernel add a level of complexity/risks.

I have run those user tests with https://github.com/Quansight/jupyterlab-kernel-usage/pull/17 so it is safe to merge it, it only adds more safety regarding this issue.

**Comment by mlucool** [comment]
I only found this as I ran into it when restarting kernels without spark/dask/... so at least some standard user cases triggers it (even if rarely). This bigger problem is that this breaks the whole server and not the UI so a page refresh does not help.

**Comment by echarles** [comment]
I have tried different strategies to get the values (separated executorpool, IOLoop.current, max number of attempts) to finally come to disable the exception throwing in case of timeout.

This last one seems to fix the issue (see screencast which typically deadlocks after 5 restart, with https://github.com/Quansight/jupyterlab-kernel-usage/pull/18 I can not replicate anymore the issue).

![Untitled5](https://user-images.githubusercontent.com/226720/169831728-706d1b38-f4d2-4510-b5f4-f642b3414a50.gif)
