### ISSUE TITLE
Merge with `jupyter-resource-usage`?

### ISSUE THREAD

**Issue by jtpio** [Quansight/jupyterlab-kernel-usage#22]
This extension looks really useful, thanks for working on this!

It looks like it could maybe be merged with the existing `jupyter-resource-usage` extension? https://github.com/jupyter-server/jupyter-resource-usage

For now `jupyter-resource-usage` only exposes a single endpoint about the total server memory usage, which also includes the memory usage of the kernels on the same machine. It would be really great if it could also expose more granular data like kernel metrics.

A possible integration of the two extensions has already been briefly discussed in https://github.com/jupyter-server/jupyter-resource-usage/issues/31 as well. So opening this issue for visibility and to evaluate whether now is a good time to reevaluate this.

**Comment by mlucool** [comment]
Yes - let's merge into jupyter-resource-usage. I think it'll benefit everyone.

**Comment by davidbrochart** [comment]
Just mentioning that Jupyverse has the [resource usage](https://github.com/jupyter-server/jupyverse/tree/main/plugins/resource_usage) plugin, equivalent to https://github.com/jupyter-server/jupyter-resource-usage. We should update it if/when `jupyterlab-kernel-usage` and `jupyter-resource-usage` are merged.

**Comment by jtpio** [comment]
> Yes - let's merge into jupyter-resource-usage. I think it'll benefit everyone.

Sounds good. If anyone feels like opening a PR that would be great, thanks!

**Comment by davidbrochart** [comment]
I opened https://github.com/jupyter-server/jupyter-resource-usage/pull/163.

**Comment by krassowski** [comment]
I was going to open a PR later, but thanks! Let's just remember to include #24 too.

**Comment by krassowski** [comment]
The new PR is https://github.com/jupyter-server/jupyter-resource-usage/pull/164

**Comment by jtpio** [comment]
Closing since https://github.com/jupyter-server/jupyter-resource-usage/pull/164 has now been merged and released: https://github.com/jupyter-server/jupyter-resource-usage/releases/tag/v0.7.0
