### ISSUE TITLE
Important Issues

### ISSUE THREAD

**Issue by nishikantparmariam** [Quansight/jupyterlab-kernel-usage#23]
Hi, I have tried this extension and found this very useful. Though this has some issues -

### Polling for shutdown kernel

If the extension is opened in the right pane and if the kernel whose info is currently being shown is shut, the extension still polls for that, and all requests give 404 kernel not found error -

![poll-for-non-existent-kernels](https://user-images.githubusercontent.com/7736252/206186798-0ac1c990-f54a-497a-a709-e7e077530242.gif)

### No. of requests being sent on notebook tab change

The extension makes nearly exponential no. of API calls in some cases which can eventually crash the server or give too many file descriptors error. Steps to reproduce - 

- Open two notebooks and the extension in the right pane
- Open the networks tab as well
- Switch between notebook tabs and notice the no. of requests being sent each time and how fast they grow in number

This can also be confirmed by adding a console log statement around [this line](https://github.com/Quansight/jupyterlab-kernel-usage/blob/b22e7f8b35f1adf7a14f0ff2d9e637c37751efa2/src/widget.tsx#L52).

### Requests go into the pending state when the kernel is busy

The extension makes API calls to get the kernel info. If there is a long-running cell say -
```
while True:
    x=1
```
all the requests go into the pending state. Likely it gets stuck at [this](https://github.com/Quansight/jupyterlab-kernel-usage/blob/b22e7f8b35f1adf7a14f0ff2d9e637c37751efa2/jupyterlab_kernel_usage/handlers.py#L44) line. After this, all other core jupyterlab requests go into pending state e.g. /sessions, /terminals etc.

### UX (Minor)

Assuming the extension is opened in the right pane. When multiple notebooks are opened and they are tab-switched, the kernel id and notebook name shown in the UI are updated very quickly, but other memory metrics corresponding to this kernel take time to show up, during this period it shows metrics of the last active notebook, which can give a false impression. A solution here would be to show a loading status?

**Comment by krassowski** [comment]
This issues were tackled in #24 which:
- fixed "No. of requests being sent on notebook tab change"
- fixed "Polling for shutdown kernel"
- alleviated "Requests go into the pending state when the kernel is busy"
- indirectly alleviated "UX (Minor)"

I released https://pypi.org/project/jupyterlab-kernel-usage/0.6.0/ as a final release from this repository. I am happy to tackle any follow up issues once this extension gets merged into `jupyter-resource-usage` as proposed in #22 (https://github.com/jupyter-server/jupyter-resource-usage/pull/164).

**Comment by krassowski** [comment]
Closing as completed. If there are any remaining issues, we can track them in the new repository: https://github.com/jupyter-server/jupyter-resource-usage.
