### ISSUE TITLE
Archive the repo?

### ISSUE THREAD

**Issue by jtpio** [Quansight/jupyterlab-kernel-usage#26]
With the merge of the extension with `jupyter-resource-usage` (https://github.com/jupyter-server/jupyter-resource-usage/releases/tag/v0.7.0), it looks like this repo could now be archived?

**Comment by jtpio** [comment]
cc @krassowski @echarles who might have the proper rights to archive the repo

**Comment by krassowski** [comment]
Archiving now after adding a notice to the README (https://github.com/Quansight/jupyterlab-kernel-usage/pull/27).

**Comment by krassowski** [comment]
Whops, I cannot archive. Pinging @echarles.

**Comment by echarles** [comment]
Done.
